### PR TITLE
Pre commit hooks

### PR DESCRIPTION
**Pull request by ebadkamil**
Add `flake8`, `black` and `isort` as `pre-commit` hooks. Updated CI with flake and black checks.

### CODE REVIEW

**Comment by umithardal** [comment]
I think we should have discussed this first. I do not like for example the styling of flake and black. Anyways, I will do a review hopefully this week. Please do not merge it until I have a good look.

**Comment by ebadkamil** [comment]
Can you change the settings of the repo to require Approval for merge.

**Comment by SkyToGround** [comment]
@ebadkamil Done.

**Comment by ebadkamil** [comment]
Thank you Jonas @SkyToGround

**Comment by umithardal** [comment]
@ebadkamil there are lots of changes in many files. Are we sure there are no breaking changes? Are they changes due to black and flake and only about formatting?

**Comment by ebadkamil** [comment]
Most of the changes are just sorting imports. And they do not break anything. I also ran the tests and they were all fine.

**Review by umithardal — APPROVED** [review]

**Pull request merged**
