### PR TITLE
Fix stop now issue with no data in file

### PR DESCRIPTION
**Pull request by ebadkamil**

### CODE REVIEW

**Review by umithardal — APPROVED** [review]
great thanks. Let us wait for Kenan to test.

**Comment by kmurica** [comment]
Seems to work and the option 1 with CTRL + C produces readable data on my local machine at least. I had to fix broken code as the topic argument was renamed to command_status_topic instead of topic. Otherwise should be fine now.

**Review by kmurica — APPROVED** [review]
LGTM.

**Comment by kmurica** [comment]
@ebadkamil could you take a look at what formatting issue it is complaining about in Jenkins? Probably caused by my commit to fix the broken code part.

**Comment by kmurica** [comment]
fixing formatting issue..

**Pull request merged**
