### PR TITLE
Sprint2107

### PR DESCRIPTION
**Pull request by kmurica**
creating PR for sprint work

### CODE REVIEW

**Comment by kmurica** [comment]
Should this be tested in ymir before merge? Can't hurt to have the PR anyway.

**Comment by ebadkamil** [comment]
LGTM.

**Review by ebadkamil — APPROVED** [review]

**Comment by umithardal** [comment]
Waiting for Ymir rather negates the purpose of the 2 weeks sprint. IMHO, we should merge and if anything comes up, new tickets should be open with corresponding PRs. We should not keep this PR open and push new code and fixes in it.

**Review by umithardal — APPROVED** [review]

**Comment by ebadkamil** [comment]
Let's merge this.

**Pull request merged**
